---
development:
  cloud_name: straydar
  api_key: '832657894521513'
  api_secret: WK7IZfNNJKXEb49KsyMi_DfOCHI
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: straydar
  api_key: '832657894521513'
  api_secret: WK7IZfNNJKXEb49KsyMi_DfOCHI
  enhance_image_tag: true
  static_image_support: true
  secure: true
test:
  cloud_name: straydar
  api_key: '832657894521513'
  api_secret: WK7IZfNNJKXEb49KsyMi_DfOCHI
  enhance_image_tag: true
  static_image_support: false
